name: Nuget Exporter
on: push
jobs:
  nugetpush:
    runs-on: ubuntu-latest
    steps:
      - name: restore
        run: dotnet restore
      - name: build nuget
        run: dotnet pack -c Release
      - name: push nuget
        run: dotnet nuget push .\popoDeterministic\bin\Release\popoDeterministic.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
